"use strict";

const ADD_TODO ="ADD_TODO",
      SHOW_ALL ="SHOW_ALL",
      SHOW_ACTIVE ="SHOW_ACTIVE",
      TOGGLE_TODO ="TOGGLE_TODO",
      SHOW_COMPLETED ="SHOW_COMPLETED",
      SET_VISIBILITY_FILTER ="SET_VISIBILITY_FILTER";

module.exports = {
	ADD_TODO,
	SHOW_ALL,
	SHOW_ACTIVE,
  TOGGLE_TODO,
  SHOW_COMPLETED,
  SET_VISIBILITY_FILTER,
};
