"use strict";

const ADD_TODO ="ADD_TODO",
      TOGGLE_TODO ="TOGGLE_TODO",
      SET_VISIBILITY_FILTER ="SET_VISIBILITY_FILTER",
      SHOW_ALL ="SHOW_ALL",
      SHOW_ACTIVE ="SHOW_ACTIVE",
      SHOW_COMPLETED ="SHOW_COMPLETED";

module.exports = {
	ADD_TODO,
	TOGGLE_TODO,
	SET_VISIBILITY_FILTER,
	SHOW_ALL,
	SHOW_ACTIVE,
	SHOW_COMPLETED
};
